persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Standard MQTT Port (for Node-RED gateway client)
listener 1883
allow_anonymous true

# WebSockets Port (required for web dashboard browser client connection)
listener 9001
protocol websockets
allow_anonymous true
